.TH BECHO 1

.SH NAME

becho - An utility to treat, style and print text to standard output.

.SH SYNOPSIS

.B becho
[\fIOPTIONS\fR]
[\fITEXT_FRAGMENTS\fR]...

.SH DESCRIPTION

Prints text to standard output with treatments and styles. It gets the
text it will handle by concatenating text fragments that were given as
arguments.

.SH OPTIONS

.TP
\fB-h\fR, \fB--help\fR
Prints short help instructions.

.TP
\fB-V\fR, \fB--version\fR
Prints the version.

.TP
\fB-v\fR, \fB--verbose\fR
Prints useful information for debugging to standard error.

.TP
\fB-e\fR, \fB--escape\fR
Escapes new line (\\n), tab (\\t) and escape (\\e, \\x1b and \\033) characters.
A tab character will be replaced by two spaces.

.TP
\fB-n\fR, \fB--no-end-new-line\fR
Do not use a new line character in the end of output.

.TP
\fB-R\fR, \fB--repeat\fR=\fINUMBER_OF_REPETITIONS\fR
Defines the number of times the output will be repeated.

.TP
\fB-I\fR, \fB--ignore-empty\fR
Ignores text fragments that, if trimmed, are an empty string.

.TP
\fB-b\fR, \fB--bold\fR
Uses bold text. It only works if your font has bold characters.

.TP
\fB-x\fR, \fB--crossed-out\fR
Uses crossed out text.

.TP
\fB-i\fR, \fB--italic\fR
Uses italic text. It only works if your font has italic characters.

.TP
\fB-u\fR, \fB--underline\fR
Uses underlined text.

.TP
\fB-f\fR, \fB--foreground-color\fR=\fICOLOR\fR
Defines the foreground color. Available colors are the ones listed in the
COLORS section. By default, it uses "normal".

.TP
\fB-g\fR, \fB--background-color\fR=\fICOLOR\fR
Defines the background color. Available colors are the ones listed in the
COLORS section. By default, it uses "normal".

.TP
\fB-d\fR, \fB--dim\fR
Uses dimmed color.

.TP
\fB-t\fR, \fB--separator\fR=\fISEPARATOR\fR
Defines the separator string to be used when concatenating the text fragments
given as arguments. By default, it uses a space.

.TP
\fB-c\fR, \fB--case\fR=\fICASE\fR
Defines the case the text will be treated to. Available cases are the ones
listed in the CASES section. By default, it uses "normal".

.TP
\fB-l\fR, \fB--left-indentation\fR=\fILEFT_INDENTATION\fR
Defines a string to be used as left indentation. By default, it uses an empty
string.

.TP
\fB-w\fR, \fB--width\fR=\fIWIDTH\fR
Defines the width of the output. By default, it will use the terminal width, or,
if it can not measure it, 80.


.SH COLORS

When applying colors, you can use values from the 8-bits palette, that goes
from 0 to 255. Alternatively, you can use a name from a color from the 4-bits
palette:

  - \fBblack\fR: same as value 0.
  - \fBlight_black\fR: same as value 8.
  - \fBred\fR: same as value 1.
  - \fBlight_red\fR: same as value 9.
  - \fBgreen\fR: same as value 2.
  - \fBlight_green\fR: same as value 10.
  - \fByellow\fR: same as value 3.
  - \fBlight_yellow\fR: same as value 11.
  - \fBblue\fR: same as value 4.
  - \fBlight_blue\fR: same as value 12.
  - \fBmagenta\fR: same as value 5.
  - \fBlight_magenta\fR: same as value 13.
  - \fBcyan\fR: same as value 6.
  - \fBlight_cyan\fR: same as value 14.
  - \fBwhite\fR: same as value 7.
  - \fBlight_white\fR: same as value 15.
  - \fBnormal (default)\fR: maintains the default colors of the terminal.


.SH CASES
These are the available cases that can be used with the case flag:

  - \fBupper\fR: all letters are in upper case.
  - \fBlower\fR: all letter are in lower case.
  - \fBcamel\fR: with exception of the first word, that is all in lower case, all
           initials are upper case and the rest of the words in lower case.
           All spacing between words is removed.
  - \fBupper_camel\fR: Same as camel, but the first word is not an exception.
  - \fBtitle\fR: all initials are in upper case and the rest of the words in lower
           case.
  - \fBsnake\fR: all letters are in lower case and separated by one underline.
  - \fBupper_snake\fR: same as snake case but all letter are in upper case.
  - \fBkebak\fR: all letters are in lower case and separated by one dash.
  - \fBupper_kebab\fR: same as kebab but all letters are in upper case.
  - \fBtitle_kebab\fR: same as kebab but the initials are in upper case and the rest
                 of the words in lower case.
  - \fBalternate\fR: alternates between the use of upper and lower case.
  - \fBnormal (default)\fR: maintains the default case of the text.


.SH AUTHOR
Sherman Rofeman <skippyr.developer@gmail.com>

Official homepage: https://github.com/skippyr/becho.


.SH COPYRIGHT
Copyright (c) 2023, Sherman Rofeman. MIT License.

