.TH BECHO

.SH NAME
becho - An utility to treat, style, format and print texts.

.SH SYNOPSIS
.B becho
[\fIOPTIONS\fR]
[\fITEXT_FRAGMENTS\fR]...

.SH DESCRIPTION
Prints text to the standart output with styles, prefix, suffix and formatting.
It can get the text it will handle by concatenating text fragments that were
given as arguments or from the standart input.

.SH OPTIONS
.TP
\fB-h\fR, \fB--help\fR
Shows a short help instructions.
.TP
\fB-b\fR, \fB--bold\fR
Uses bold text.
.TP
\fB-x\fR, \fB--crossed-out\fR
Uses crossed out text.
.TP
\fB-i\fR, \fB--italic\fR
Uses italic text. It only works if your font has italic characters.
.TP
\fB-f\fR, \fB--foreground-color\fR=\fICOLOR\fR
Changes the foreground color. Available colors are the ones listed in the
COLORS section. By default, it uses "normal".
.TP
\fB-g\fR, \fB--background-color\fR=\fICOLOR\fR
Changes the background color. Available colors are the ones listed in the
COLORS section. By default, it uses "normal".
.TP
\fB-d\fR, \fB--dim\fR
Uses dimmed color.
.TP
\fB--separator\fR=\fIseparator\fR
Specifies the separator string to be used when concatenating the text fragments
given as arguments. It does not affect text coming from the standart input. By
default, it uses an empty string.

.SH COLORS
These are the available colors you can uses for color flags:

  - black
  - dark_red
  - red
  - dark_green
  - green
  - dark_yellow
  - yellow
  - dark_blue
  - blue
  - dark_magenta
  - magenta
  - dark_cyan
  - cyan
  - white
  - normal (default)

.SH AUTHOR
Sherman Rofeman <skippyr.development@gmail.com>

Official homepage: https://github.com/skippyr/becho.

.SH COPYRIGHT
Copyright © Sherman Rofeman, 2023. MIT License.

