.TH BECHO

.SH NAME

becho - An utility to treat, style, format and print texts.

.SH SYNOPSIS

.B becho
[\fIOPTIONS\fR]
[\fITEXT_FRAGMENTS\fR]...

.SH DESCRIPTION

Prints text to the standart output with styles, prefix, suffix and formatting.
It can get the text it will handle by concatenating text fragments that were
given as arguments or from the standart input.

.SH OPTIONS

.TP
\fB-h\fR, \fB--help\fR
Shows a short help instructions.

.TP
\fB-e\fR, \fB--escape\fR
Escapes new line and tab sequences. A tab sequence will be replaced by two
spaces.

.TP
\fB-b\fR, \fB--bold\fR
Uses bold text. It only works if your font has bold characters.

.TP
\fB-x\fR, \fB--crossed-out\fR
Uses crossed out text.

.TP
\fB-i\fR, \fB--italic\fR
Uses italic text. It only works if your font has italic characters.

.TP
\fB-u\fR, \fB--underline\fR
Uses underlined text.

.TP
\fB-f\fR, \fB--foreground-color\fR=\fICOLOR\fR
Changes the foreground color. Available colors are the ones listed in the
COLORS section. By default, it uses "normal".

.TP
\fB-g\fR, \fB--background-color\fR=\fICOLOR\fR
Changes the background color. Available colors are the ones listed in the
COLORS section. By default, it uses "normal".

.TP
\fB-d\fR, \fB--dim\fR
Uses dimmed color.

.TP
\fB-t\fR, \fB--separator\fR=\fISEPARATOR\fR
Specifies the separator string to be used when concatenating the text fragments
given as arguments. It does not affect text coming from the standart input. By
default, it uses an empty string.

.TP
\fB-c\fR, \fB--case\fR=\fICASE\fR
Specifies the case the text will be treated to. Available cases are the ones
listed in the CASES section. By default, it uses "normal".

.SH COLORS
These are the available colors from the 4-bits pallete you can use for color
flags:

  - black
  - dark_red
  - red
  - dark_green
  - green
  - dark_yellow
  - yellow
  - dark_blue
  - blue
  - dark_magenta
  - magenta
  - dark_cyan
  - cyan
  - white
  - normal (default): maintains the default colors of the terminal.

You can also use a value from the 8-bits pallete, that goes from 0 to 255. This
pallete also includes the 4-bits pallete and can be used instead of using the
name of the color.

.SH CASES
These are the available cases that can be used with the case flag:

  - upper: all letters are in upper case.
  - lower: all letter are in lower case.
  - camel: with exception of the first word, that is all in lower case, all
           initials are upper case and the rest of the words in lower case.
           All spacing between words is removed.
  - upper_camel: Same as camel, but the first word is not an exception.
  - title: all initials are in upper case and the rest of the words in lower
           case.
  - snake: all letters are in lower case and separated by one underline.
  - screaming_snake: same as snake case but all letter are in upper case.
  - kebak: all letters are in lower case and separated by one dash.
  - upper_kebab: same as kebab but all letters are in upper case.
  - train: same as kebab but the initials are in upper case and the rest of the
           words in lower case.
  - normal (default): maintains the default case of the text.

.SH AUTHOR
Sherman Rofeman <skippyr.developer@gmail.com>

Official homepage: https://github.com/skippyr/becho.

.SH COPYRIGHT
Copyright © Sherman Rofeman, 2023. MIT License.

